# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the UWRF Course Scheduler backend."""

import os

block_cipher = None

a = Analysis(
    ['run_server.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('alembic', 'alembic'),
        ('alembic.ini', '.'),
        ('app/templates', 'app/templates'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'fastapi',
        'starlette',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'sqlalchemy',
        'sqlalchemy.sql.default_comparator',
        'alembic',
        'jose',
        'jose.jwt',
        'jose.backends',
        'jose.backends.cryptography_backend',
        'passlib',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'bcrypt',
        'multipart',
        'python_multipart',
        'pydantic',
        'pydantic_settings',
        'jinja2',
        'openpyxl',
        'requests',
        'icalendar',
        'pytz',
        'app',
        'app.main',
        'app.database',
        'app.models',
        'app.models.base',
        'app.models.term',
        'app.models.building',
        'app.models.room',
        'app.models.instructor',
        'app.models.course',
        'app.models.section',
        'app.models.meeting',
        'app.models.time_block',
        'app.models.term_session',
        'app.models.settings',
        'app.models.dismissed_warning',
        'app.models.enrollment_record',
        'app.models.academic_year',
        'app.models.course_rotation',
        'app.models.course_prerequisite',
        'app.models.load_adjustment',
        'app.models.instructor_note',
        'app.schemas',
        'app.schemas.schemas',
        'app.api',
        'app.api.routes',
        'app.api.routes.terms',
        'app.api.routes.buildings',
        'app.api.routes.rooms',
        'app.api.routes.instructors',
        'app.api.routes.courses',
        'app.api.routes.sections',
        'app.api.routes.meetings',
        'app.api.routes.time_blocks',
        'app.api.routes.import_export',
        'app.api.routes.suggestions',
        'app.api.routes.analytics',
        'app.api.routes.export_html',
        'app.api.routes.settings',
        'app.api.routes.academic_years',
        'app.api.routes.prerequisites',
        'app.api.routes.rotation',
        'app.api.routes.load_adjustments',
        'app.services',
        'app.services.conflict_engine',
        'app.services.soft_constraints',
        'app.services.suggestion_engine',
        'app.services.term_validation',
        'app.services.export',
        'app.services.html_export',
        'app.services.xlsx_reader',
        'app.services.xlsx_schedule_parser',
        'app.services.session_dates',
        'app.services.schedule_compare',
        'app.services.workload',
        'app.services.workload_export',
        'app.seed',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='course_scheduler',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='course_scheduler',
)
