"""add instructor_availability_templates table

Revision ID: 91fb75a5b25b
Revises: a68c7a7ecb81
Create Date: 2026-04-05 20:01:12.827158

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fb75a5b25b'
down_revision: Union[str, None] = 'a68c7a7ecb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_availability_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('term_type', sa.String(length=10), nullable=False),
    sa.Column('day_of_week', sa.String(length=3), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('type', sa.Enum('unavailable', 'prefer_avoid', name='availabilitytype'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instructor_id', 'term_type', 'day_of_week', 'start_time', name='uq_template_slot')
    )
    op.create_foreign_key(None, 'course_rotations', 'time_blocks', ['time_block_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'course_rotations', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'course_rotations', 'instructors', ['instructor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'terms', 'academic_years', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terms', type_='foreignkey')
    op.drop_constraint(None, 'course_rotations', type_='foreignkey')
    op.drop_constraint(None, 'course_rotations', type_='foreignkey')
    op.drop_constraint(None, 'course_rotations', type_='foreignkey')
    op.drop_table('instructor_availability_templates')
    # ### end Alembic commands ###
