"""add instructor_id to sections

Revision ID: a06a39524b91
Revises: 3b09ff1f9d92
Create Date: 2026-02-17 10:16:13.355591

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06a39524b91'
down_revision: Union[str, None] = '3b09ff1f9d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sections', 'instructors', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'instructor_id')
    # ### end Alembic commands ###
