"""add summer sessions support

Revision ID: bd35774985a2
Revises: d1f4e14cdc49
Create Date: 2026-03-04 14:58:38.892247

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd35774985a2'
down_revision: Union[str, None] = 'd1f4e14cdc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'name')
    )
    op.add_column('sections', sa.Column('duration_weeks', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('sections', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'end_date')
    op.drop_column('sections', 'start_date')
    op.drop_column('sections', 'duration_weeks')
    op.drop_table('term_sessions')
    # ### end Alembic commands ###
